name: 'coverage'
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main","coverage"]

jobs:

  coverage:
    # environment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: gen coverage 
        uses: romeovs/lcov-reporter-action@v0.2.16
          with:
            lcov-file: ./lcov.info
