on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: 5monkeys/cobertura-action@master
        with:
          path: coverage_output/cobertura-coverage.xml
          # minimum_coverage: 75